### ISSUE TITLE
coverage directory

### ISSUE THREAD

**Issue by dotdat** [sublimino/karma-story-reporter#7]
Should the NPM package for this, contained here: https://registry.npmjs.org/karma-story-reporter/-/karma-story-reporter-0.2.2.tgz contain the multitude of coverage files?

**Comment by sublimino** [comment]
Absolutely not! I hadn't unpacked what I pushed to NPM before, apologies. Only a few kilobytes, fortunately. 

I failed to follow through with this commit apparently https://github.com/sublimino/karma-story-reporter/commit/6b7f7af1965d539fab1967bd003496f19d98d15e so have just pushed 0.3.1 to NPM.
